name: auto_parts_app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.0
  provider: ^6.0.5
  flutter_chat_ui: ^1.6.7
  image_picker: ^1.0.4

flutter:
  uses-material-design: true
